
controller:

  resources:
    requests:
      cpu: 750m
      memory: 750Mi

  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"

  tolerations:
  - key: "workload"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

  service:
    type: LoadBalancer
    enableHttp: true
    enableHttps: true
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"

  config:
    log-format-upstream: '{"time": "$time_iso8601", "remote_addr": "$remote_addr", "request_id": "$req_id", "http_traceparent": "$http_traceparent", "http_correlation_id": "$sent_http_x_correlation_id", "bytes_sent": $bytes_sent, "request_time": $request_time, "status": $status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time,"method": "$request_method", "http_referrer": "$http_referer","http_user_agent": "$http_user_agent", "upstream_addr": "$upstream_addr", "response_length": "$upstream_response_length", "response_time": "$upstream_response_time", "response_status": "$upstream_status" }'
    proxy-read-timeout: "120"
    enable-modsecurity: "true"
    log-level: "debug"